[project]
name = "skrybek"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlx-vlm>=0.3.3",
    "mlx-whisper>=0.4.2",
    "numpy>=2.2.6",
    "pyperclip>=1.9.0",
    "scipy>=1.16.1",
    "sounddevice>=0.5.2",
]
